// 100% local hardcoded garage data — no live API or DB calls.

export const initialVehicles = [
  {
    id: 1,
    brand: 'Mercedes-Benz',
    model: 'A 180D',
    nickname: 'Mercedes A 180D',
    year: 2015,
    label: '2015 Mercedes-Benz A 180D',
    emoji: '🚗',
    plate: 'MH 12 LS 0049',
    class: 'hatchback',
    completion: 92,
    health: 92,
    mileage: '62,400',
    fuelEff: '20.1',
    marketValue: '₹8,50,000',
    tco: '₹41,200',
    power: '109 bhp',
    topSpeed: '190 kmph',
    engine: '1796 cc',
    color: 'Cosmos Black',
    img: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=450&fit=crop',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg',
  },
  {
    id: 2,
    brand: 'Mercedes-Benz',
    model: 'E 250D',
    nickname: 'Mercedes E 250D',
    year: 1996,
    label: '1996 Mercedes-Benz E 250D',
    emoji: '🚗',
    plate: 'KL 07 AM 9181',
    class: 'sedan',
    completion: 88,
    health: 88,
    mileage: '180,000',
    fuelEff: '11.8',
    marketValue: '₹3,20,000',
    tco: '₹28,000',
    power: '113 bhp',
    topSpeed: '193 kmph',
    engine: '2497 cc',
    color: 'Brilliant Silver',
    img: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=450&fit=crop',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg',
  },
  {
    id: 4,
    brand: 'Honda',
    model: 'CRV RVSi',
    nickname: 'Honda CRV RVSi',
    year: 2009,
    label: '2009 Honda CRV RVSi',
    emoji: '🚙',
    plate: 'KL 09 AV 8668',
    class: 'suv',
    completion: 90,
    health: 90,
    mileage: '120,500',
    fuelEff: '11.1',
    marketValue: '₹4,10,000',
    tco: '₹22,000',
    power: '161 bhp',
    topSpeed: '190 kmph',
    engine: '1997 cc',
    color: 'Alabaster Silver',
    img: 'https://images.unsplash.com/photo-1606577924006-27d39b132ae2?w=800&h=450&fit=crop',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Honda_Logo.svg',
  },
  {
    id: 3,
    brand: 'Piaggio',
    model: 'Vespa VX 125',
    nickname: 'Vespa VX 125',
    year: 2014,
    label: '2014 Piaggio Vespa VX 125',
    emoji: '🛵',
    plate: 'KL 07 AM 9181',
    class: 'scooter',
    completion: 96,
    health: 96,
    mileage: '34,200',
    fuelEff: '45.2',
    marketValue: '₹48,000',
    tco: '₹6,400',
    power: '10.1 bhp',
    topSpeed: '91 kmph',
    engine: '125 cc',
    color: 'Rosso Dragon',
    img: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&h=450&fit=crop',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Vespa_logo.svg',
  },
];

// Brand logo lookup
export const brandLogos = {
  'Mercedes-Benz': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Mercedes-Logo.svg/120px-Mercedes-Logo.svg.png',
  'Royal Enfield': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Royal_Enfield_logo.svg/512px-Royal_Enfield_logo.svg.png',
  'Piaggio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Piaggio_logo.svg/120px-Piaggio_logo.svg.png',
  'Honda': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Honda_logo.svg/120px-Honda_logo.svg.png',
  'Maruti Suzuki': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Maruti_Suzuki_Logo.svg/120px-Maruti_Suzuki_Logo.svg.png',
  'Tata': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Tata_logo.svg/120px-Tata_logo.svg.png',
  'Hyundai': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Hyundai_Motor_Company_logo.svg/120px-Hyundai_Motor_Company_logo.svg.png',
  'Toyota': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Toyota_carlogo.svg/120px-Toyota_carlogo.svg.png',
  'BMW': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/120px-BMW.svg.png',
  'Audi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Audi-Logo_2016.svg/120px-Audi-Logo_2016.svg.png',
  'Volkswagen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Volkswagen_logo_2019.svg/120px-Volkswagen_logo_2019.svg.png',
  'Kia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Kia-logo.svg/120px-Kia-logo.svg.png',
  'Mahindra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Mahindra_new_logo.svg/120px-Mahindra_new_logo.svg.png',
};

// Mock marketplace feed
export const mockMarketListings = [
  {
    id: 'm1',
    name: '18-inch BBS LM Alloy Wheels',
    price: '₹65,000',
    badge: '🔥 Hot Deal',
    img: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=400&h=500&fit=crop',
    tall: true,
    seller: 'Rohan C.',
    location: 'Mumbai',
    km: null,
    desc: 'Genuine BBS LM forged set of 4. 18×8.5J ET35. 5×112 PCD. Light kerb rash on 1 wheel.',
    cat: 'Wheels',
    category: 'Performance',
  },
  {
    id: 'm2',
    name: 'Akrapovic Carbon Slip-on Exhaust',
    price: '₹42,000',
    badge: '🟢 Fair Price',
    img: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=380&fit=crop',
    tall: false,
    seller: 'Tanmay N.',
    location: 'Delhi',
    km: null,
    desc: 'Genuine Akrapovic slip-on with carbon end-cap. Saves 1.2 kg over OEM. Universal Honda Civic FK fitment.',
    cat: 'Exhaust',
    category: 'Performance',
  },
  {
    id: 'm3',
    name: '2015 Volkswagen Polo GT TSI',
    price: '₹5,20,000',
    badge: '🔥 Hot Deal',
    img: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400&h=500&fit=crop',
    tall: true,
    seller: 'Aarav K.',
    location: 'Bangalore',
    km: '64,000 km',
    desc: '1.2L TSI petrol, 7-speed DSG. Single owner, full VW service history. Stage 1 remap @ 138 bhp.',
    cat: 'Hatchback',
    category: 'Vehicles',
  },
  {
    id: 'm4',
    name: 'K&N High Flow Air Filter',
    price: '₹6,500',
    badge: '🟢 Fair Price',
    img: 'https://images.unsplash.com/photo-1532974297617-c0f05fe48bff?w=400&h=380&fit=crop',
    tall: false,
    seller: 'Siddharth P.',
    location: 'Pune',
    km: null,
    desc: 'Brand new in box. Washable, reusable, lifetime warranty. Universal fitment for Civic / City / Verna.',
    cat: 'Intake',
    category: 'Performance',
  },
  {
    id: 'm5',
    name: 'Brembo Big Brake Kit',
    price: '₹1,10,000',
    badge: '🔥 Hot Deal',
    img: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400&h=500&fit=crop',
    tall: true,
    seller: 'Karan V.',
    location: 'Hyderabad',
    km: null,
    desc: 'Brembo GT 4-piston front BBK with 355mm 2-piece slotted rotors. Includes lines & pads. 5×114.3 fitment.',
    cat: 'Brakes',
    category: 'Performance',
  },
];

export const brandCatalogue = {
  'Mercedes-Benz': {
    models: ['A 180D', 'A-Class', 'C-Class C200', 'E-Class', 'GLA 200', 'GLC 300', 'S-Class', 'AMG GT', 'AMG GT R', 'AMG GT 63 S'],
    yearRange: [1980, 2024],
  },
  'Royal Enfield': {
    models: ['Classic 350', 'Bullet 350', 'Meteor 350', 'Himalayan', 'Hunter 350', 'Continental GT', 'Interceptor 650'],
    yearRange: [1950, 2024],
  },
  'Honda': {
    models: ['City', 'Civic', 'CR-V 2.0L AWD', 'Jazz', 'Amaze', 'WR-V', 'Elevate'],
    yearRange: [1985, 2024],
  },
  'Maruti Suzuki': {
    models: ['Swift', 'Baleno', 'Dzire', 'Vitara Brezza', 'Ertiga', 'XL6'],
    yearRange: [1983, 2024],
  },
  'Tata': {
    models: ['Nexon', 'Punch', 'Harrier', 'Safari', 'Nexon EV', 'Tigor EV'],
    yearRange: [1991, 2024],
  },
  'Hyundai': {
    models: ['i20', 'Creta', 'Venue', 'Tucson', 'Alcazar', 'Ioniq 5'],
    yearRange: [1996, 2024],
  },
  'Toyota': {
    models: ['Innova Crysta', 'Fortuner', 'Camry', 'Glanza', 'Urban Cruiser Hyryder'],
    yearRange: [1990, 2024],
  },
  'Mahindra': {
    models: ['Scorpio-N', 'XUV700', 'Thar', 'XUV300', 'Bolero'],
    yearRange: [1994, 2024],
  },
  'Kia': {
    models: ['Seltos', 'Sonet', 'Carens', 'EV6'],
    yearRange: [2019, 2024],
  },
  'BMW': {
    models: ['3 Series', '5 Series', 'X1', 'X3', 'X5', 'M3'],
    yearRange: [1985, 2024],
  },
  'Audi': {
    models: ['A4', 'A6', 'Q3', 'Q5', 'Q7', 'e-tron'],
    yearRange: [1990, 2024],
  },
  'Volkswagen': {
    models: ['Polo', 'Polo GT TSI', 'Vento', 'Virtus', 'Taigun', 'Tiguan'],
    yearRange: [1985, 2024],
  },
};